from snakemake.utils import min_version
import pandas as pd 
from os.path import dirname, basename
min_version("6.0")
configfile: "config/config.yaml"

# Todo: add schema validation to config, samples files...
samples = pd.read_csv(config["samples"], sep = '\t').set_index("sample", drop=False)

rule all:
    input:
        expand("results/rsem/{sample}_{genome}/{sample}_{genome}.isoforms.results", sample=samples.index, genome = config["genome"]["build"]),
        expand("results/fastqc/{sample}_{read}.html", sample=samples.index, read = ["R1", "R2"]),
        "results/multiqc/multiqc-report.html"
        
include: "rules/fastqc.smk"
include: "rules/star.smk"
include: "rules/rsem.smk"
include: "rules/multiqc.smk"
